# this travis file only builds the lara-plugin, a built of the R package is not required or desired

dist: trusty

language:
  - node_js
  - ruby

node_js:
  - "8"

sudo: false

cache:
  bundler: true
  pip: true
  npm: true
before_install:
- pyenv local 3.6
- cd lara-plugin
install:
- travis_retry gem install s3_website -v 3.4.0
- travis_retry pip install awscli --upgrade --user
- travis_retry npm ci
script:
- npm run build
after_script:
- ./s3_deploy.sh
